import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillInstagram,
} from "react-icons/ai";
import Image from "next/image";
import logo from "../public/logo.png";
import avatar from "../public/avatar.png";
import { useState } from "react";
import Link from "next/link";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Varshith Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="px-10 md:px-20 lg:px-36 dark:bg-gray-900">
        <nav className="py-8 px-2 flex items-center justify-between">
          <Image src={logo} className="w-10 h-10 cursor-pointer" />
          <ul className="flex items-center">
            <li>
              <BsFillMoonStarsFill
                onClick={() => setDarkMode(!darkMode)}
                className="cursor-pointer text-2xl dark:text-white"
              />
            </li>
            <li>
              <a
                className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white py-2 px-4 rounded-md ml-8"
                href="#"
              >
                Resume
              </a>
            </li>
          </ul>
        </nav>
      </header>
      <main className="px-10 pb-8 md:px-20 lg:px-36 dark:bg-gray-900">
        <section className="flex flex-col items-center justify-between md:flex-row">
          <div>
            <div className="text-center p-10">
              <h2 className="text-4xl py-2 text-cyan-500 font-medium">
                Varshith Puligadda
              </h2>
              <h3 className="text-2xl py-2 dark:text-white">
                Developer and Designer
              </h3>
              <p className="text-md py-2 md:text-lg dark:text-gray-400">
                Join me below and let's get cracking!
              </p>
            </div>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-800 dark:text-white">
              <Link
                href={{ pathname: "https://twitter.com/varshithp1" }}
                target="_blank"
              >
                <AiFillTwitterCircle />
              </Link>
              <Link
                href={{
                  pathname:
                    "https://linkedin.com/in/varshith-puligadda-1a1530237",
                }}
                target="_blank"
              >
                <AiFillLinkedin />
              </Link>
              <Link
                href={{ pathname: "https://www.instagram.com/varshith_9/" }}
                target="_blank"
              >
                <AiFillInstagram />
              </Link>
            </div>
          </div>
          <div className="bg-gradient-to-b from-cyan-500 to-teal-500 rounded-full w-60 h-60 mx-auto my-12 flex items-center md:w-70 md:h-70 md:mx-0 lg:w-80 lg:h-80">
            <Image src={avatar} />
          </div>
        </section>
        <section className="shadow-lg py-2 mt-4 rounded-xl dark:bg-white">
          <h3 className="text-3xl text-cyan-500 font-medium my-6 text-center">
            About ME!
          </h3>
          <p className="text-md text-center px-10 pb-10 md:px-20 md:text-lg">
            I don't like to define myself by the work I've done. I define myself
            by the work I want to do. Skills can be acquired, personality is
            inherit. I prefer to keep learning, continue challenging myself, and
            do interesting things that matter.
          </p>
          <p className="text-md text-center px-10 pb-10 md:px-20 md:text-lg">
            I am passionate, expressive, multi-talented spirit with a natural
            ability to entertain and inspire. I like to develop expertise in a
            number of areas over the course of my life and career.
          </p>
        </section>
      </main>
    </div>
  );
}
